// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function ComputeMetrics(arg1, arg2) {
  return window['go']['main']['App']['ComputeMetrics'](arg1, arg2);
}

export function ExportPassesToCSV(arg1, arg2) {
  return window['go']['main']['App']['ExportPassesToCSV'](arg1, arg2);
}

export function ExportTradesToCSV(arg1, arg2) {
  return window['go']['main']['App']['ExportTradesToCSV'](arg1, arg2);
}

export function OpenOptimizerFileDialog() {
  return window['go']['main']['App']['OpenOptimizerFileDialog']();
}

export function OpenTesterFileDialog() {
  return window['go']['main']['App']['OpenTesterFileDialog']();
}

export function ParseOptimizerReport(arg1) {
  return window['go']['main']['App']['ParseOptimizerReport'](arg1);
}

export function ParseTesterReport(arg1) {
  return window['go']['main']['App']['ParseTesterReport'](arg1);
}

export function SaveCSVFile(arg1, arg2) {
  return window['go']['main']['App']['SaveCSVFile'](arg1, arg2);
}
