// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {models} from '../models';

export function ComputeMetrics(arg1:Array<models.Deal>,arg2:number):Promise<models.TesterMetrics>;

export function ExportPassesToCSV(arg1:models.OptimizerReport,arg2:string):Promise<void>;

export function ExportTradesToCSV(arg1:Array<models.Deal>,arg2:string):Promise<void>;

export function OpenOptimizerFileDialog():Promise<string>;

export function OpenTesterFileDialog():Promise<string>;

export function ParseOptimizerReport(arg1:string):Promise<models.OptimizerReport>;

export function ParseTesterReport(arg1:string):Promise<models.ParsedTesterReport>;

export function SaveCSVFile(arg1:string,arg2:string):Promise<void>;
